data_processing_params:
  test_size: 0.15
  random_state: 20

random_forest:
  param_grid:
    n_estimators: [50, 100, 200]
    criterion: ['gini', 'entropy']
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ['auto', 'sqrt', 'log2']
    bootstrap: [True, False]

decision_tree:
  param_grid:
    criterion: ['gini', 'entropy']
    splitter: ['best', 'random']
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: [None, 'sqrt', 'log2']
    
xgboost:
  param_grid:
    learning_rate: [0.1, 0.01, 0.001]
    n_estimators: [50, 100, 200]
    max_depth: [3, 5, 7]
    min_child_weight: [1, 3, 5]
    gamma: [0, 0.1, 0.2]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.8, 0.9, 1.0]
    scale_pos_weight: [1, 2, 3]
